//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountRecovery) DeepCopyInto(out *AccountRecovery) {
	*out = *in
	out.Endpoint = in.Endpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountRecovery.
func (in *AccountRecovery) DeepCopy() *AccountRecovery {
	if in == nil {
		return nil
	}
	out := new(AccountRecovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccoutnRecoveryEndpoint) DeepCopyInto(out *AccoutnRecoveryEndpoint) {
	*out = *in
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccoutnRecoveryEndpoint.
func (in *AccoutnRecoveryEndpoint) DeepCopy() *AccoutnRecoveryEndpoint {
	if in == nil {
		return nil
	}
	out := new(AccoutnRecoveryEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Adaptive) DeepCopyInto(out *Adaptive) {
	*out = *in
	out.ExecutionSupervisor = in.ExecutionSupervisor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Adaptive.
func (in *Adaptive) DeepCopy() *Adaptive {
	if in == nil {
		return nil
	}
	out := new(Adaptive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminService) DeepCopyInto(out *AdminService) {
	*out = *in
	out.Wsdl = in.Wsdl
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminService.
func (in *AdminService) DeepCopy() *AdminService {
	if in == nil {
		return nil
	}
	out := new(AdminService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth) DeepCopyInto(out *Auth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth.
func (in *Auth) DeepCopy() *Auth {
	if in == nil {
		return nil
	}
	out := new(Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthEndpoint) DeepCopyInto(out *AuthEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthEndpoint.
func (in *AuthEndpoint) DeepCopy() *AuthEndpoint {
	if in == nil {
		return nil
	}
	out := new(AuthEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthFramework) DeepCopyInto(out *AuthFramework) {
	*out = *in
	out.Endpoint = in.Endpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthFramework.
func (in *AuthFramework) DeepCopy() *AuthFramework {
	if in == nil {
		return nil
	}
	out := new(AuthFramework)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthFrameworkEndpoint) DeepCopyInto(out *AuthFrameworkEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthFrameworkEndpoint.
func (in *AuthFrameworkEndpoint) DeepCopy() *AuthFrameworkEndpoint {
	if in == nil {
		return nil
	}
	out := new(AuthFrameworkEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	out.Consent = in.Consent
	out.Authenticator = in.Authenticator
	out.Endpoint = in.Endpoint
	out.Adaptive = in.Adaptive
	out.JitProvisioning = in.JitProvisioning
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authenticator) DeepCopyInto(out *Authenticator) {
	*out = *in
	out.Basic = in.Basic
	out.Totp = in.Totp
	out.EmailOtp = in.EmailOtp
	out.SmsOtp = in.SmsOtp
	out.MagicLink = in.MagicLink
	out.Fido = in.Fido
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authenticator.
func (in *Authenticator) DeepCopy() *Authenticator {
	if in == nil {
		return nil
	}
	out := new(Authenticator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Basic) DeepCopyInto(out *Basic) {
	*out = *in
	out.Parameters = in.Parameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Basic.
func (in *Basic) DeepCopy() *Basic {
	if in == nil {
		return nil
	}
	out := new(Basic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicParameters) DeepCopyInto(out *BasicParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicParameters.
func (in *BasicParameters) DeepCopy() *BasicParameters {
	if in == nil {
		return nil
	}
	out := new(BasicParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarbonHealthCheck) DeepCopyInto(out *CarbonHealthCheck) {
	*out = *in
	out.HealthChecker = in.HealthChecker
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonHealthCheck.
func (in *CarbonHealthCheck) DeepCopy() *CarbonHealthCheck {
	if in == nil {
		return nil
	}
	out := new(CarbonHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Catalina) DeepCopyInto(out *Catalina) {
	*out = *in
	out.Valves = in.Valves
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Catalina.
func (in *Catalina) DeepCopy() *Catalina {
	if in == nil {
		return nil
	}
	out := new(Catalina)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Clustering) DeepCopyInto(out *Clustering) {
	*out = *in
	out.Properties = in.Properties
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Clustering.
func (in *Clustering) DeepCopy() *Clustering {
	if in == nil {
		return nil
	}
	out := new(Clustering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusteringProperties) DeepCopyInto(out *ClusteringProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusteringProperties.
func (in *ClusteringProperties) DeepCopy() *ClusteringProperties {
	if in == nil {
		return nil
	}
	out := new(ClusteringProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configurations) DeepCopyInto(out *Configurations) {
	*out = *in
	out.Server = in.Server
	out.SuperAdmin = in.SuperAdmin
	out.UserStore = in.UserStore
	out.Database = in.Database
	out.Transport = in.Transport
	out.KeyStore = in.KeyStore
	out.TrustStore = in.TrustStore
	out.Identity = in.Identity
	out.AccountRecovery = in.AccountRecovery
	out.Monitoring = in.Monitoring
	out.Hazelcast = in.Hazelcast
	out.Authentication = in.Authentication
	out.Recaptcha = in.Recaptcha
	out.OutputAdapter = in.OutputAdapter
	out.Clustering = in.Clustering
	out.TenantMgt = in.TenantMgt
	out.TenantContext = in.TenantContext
	out.AdminService = in.AdminService
	out.SystemRoles = in.SystemRoles
	out.CarbonHealthCheck = in.CarbonHealthCheck
	out.SystemApplications = in.SystemApplications
	out.Catalina = in.Catalina
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configurations.
func (in *Configurations) DeepCopy() *Configurations {
	if in == nil {
		return nil
	}
	out := new(Configurations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Consent) DeepCopyInto(out *Consent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Consent.
func (in *Consent) DeepCopy() *Consent {
	if in == nil {
		return nil
	}
	out := new(Consent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceHealthCheckerProperties) DeepCopyInto(out *DataSourceHealthCheckerProperties) {
	*out = *in
	out.Monitored = in.Monitored
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceHealthCheckerProperties.
func (in *DataSourceHealthCheckerProperties) DeepCopy() *DataSourceHealthCheckerProperties {
	if in == nil {
		return nil
	}
	out := new(DataSourceHealthCheckerProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	out.UserDb = in.UserDb
	out.IdentityDb = in.IdentityDb
	out.SharedDb = in.SharedDb
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Database.
func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasourceHealthChecker) DeepCopyInto(out *DatasourceHealthChecker) {
	*out = *in
	out.Properties = in.Properties
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasourceHealthChecker.
func (in *DatasourceHealthChecker) DeepCopy() *DatasourceHealthChecker {
	if in == nil {
		return nil
	}
	out := new(DatasourceHealthChecker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Email) DeepCopyInto(out *Email) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Email.
func (in *Email) DeepCopy() *Email {
	if in == nil {
		return nil
	}
	out := new(Email)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailOtp) DeepCopyInto(out *EmailOtp) {
	*out = *in
	out.Parameters = in.Parameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailOtp.
func (in *EmailOtp) DeepCopy() *EmailOtp {
	if in == nil {
		return nil
	}
	out := new(EmailOtp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailOtpParameters) DeepCopyInto(out *EmailOtpParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailOtpParameters.
func (in *EmailOtpParameters) DeepCopy() *EmailOtpParameters {
	if in == nil {
		return nil
	}
	out := new(EmailOtpParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointAuth) DeepCopyInto(out *EndpointAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointAuth.
func (in *EndpointAuth) DeepCopy() *EndpointAuth {
	if in == nil {
		return nil
	}
	out := new(EndpointAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionSupervisor) DeepCopyInto(out *ExecutionSupervisor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionSupervisor.
func (in *ExecutionSupervisor) DeepCopy() *ExecutionSupervisor {
	if in == nil {
		return nil
	}
	out := new(ExecutionSupervisor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Fido) DeepCopyInto(out *Fido) {
	*out = *in
	out.Parameters = in.Parameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Fido.
func (in *Fido) DeepCopy() *Fido {
	if in == nil {
		return nil
	}
	out := new(Fido)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FidoParameters) DeepCopyInto(out *FidoParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FidoParameters.
func (in *FidoParameters) DeepCopy() *FidoParameters {
	if in == nil {
		return nil
	}
	out := new(FidoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hazelcast) DeepCopyInto(out *Hazelcast) {
	*out = *in
	out.HazelcastShutdownHook = in.HazelcastShutdownHook
	out.Logging = in.Logging
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hazelcast.
func (in *Hazelcast) DeepCopy() *Hazelcast {
	if in == nil {
		return nil
	}
	out := new(Hazelcast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastShutdownHook) DeepCopyInto(out *HazelcastShutdownHook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastShutdownHook.
func (in *HazelcastShutdownHook) DeepCopy() *HazelcastShutdownHook {
	if in == nil {
		return nil
	}
	out := new(HazelcastShutdownHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthChecker) DeepCopyInto(out *HealthChecker) {
	*out = *in
	out.DatasourceHealthChecker = in.DatasourceHealthChecker
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthChecker.
func (in *HealthChecker) DeepCopy() *HealthChecker {
	if in == nil {
		return nil
	}
	out := new(HealthChecker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Https) DeepCopyInto(out *Https) {
	*out = *in
	out.Properties = in.Properties
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Https.
func (in *Https) DeepCopy() *Https {
	if in == nil {
		return nil
	}
	out := new(Https)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpsProperties) DeepCopyInto(out *HttpsProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpsProperties.
func (in *HttpsProperties) DeepCopy() *HttpsProperties {
	if in == nil {
		return nil
	}
	out := new(HttpsProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Identity) DeepCopyInto(out *Identity) {
	*out = *in
	out.AuthFramework = in.AuthFramework
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Identity.
func (in *Identity) DeepCopy() *Identity {
	if in == nil {
		return nil
	}
	out := new(Identity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDb) DeepCopyInto(out *IdentityDb) {
	*out = *in
	out.PoolOptions = in.PoolOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDb.
func (in *IdentityDb) DeepCopy() *IdentityDb {
	if in == nil {
		return nil
	}
	out := new(IdentityDb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDbPoolOptions) DeepCopyInto(out *IdentityDbPoolOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDbPoolOptions.
func (in *IdentityDbPoolOptions) DeepCopy() *IdentityDbPoolOptions {
	if in == nil {
		return nil
	}
	out := new(IdentityDbPoolOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Internal) DeepCopyInto(out *Internal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Internal.
func (in *Internal) DeepCopy() *Internal {
	if in == nil {
		return nil
	}
	out := new(Internal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JitProvisioning) DeepCopyInto(out *JitProvisioning) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JitProvisioning.
func (in *JitProvisioning) DeepCopy() *JitProvisioning {
	if in == nil {
		return nil
	}
	out := new(JitProvisioning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Jmx) DeepCopyInto(out *Jmx) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Jmx.
func (in *Jmx) DeepCopy() *Jmx {
	if in == nil {
		return nil
	}
	out := new(Jmx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyStore) DeepCopyInto(out *KeyStore) {
	*out = *in
	out.Primary = in.Primary
	out.Internal = in.Internal
	out.Tls = in.Tls
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyStore.
func (in *KeyStore) DeepCopy() *KeyStore {
	if in == nil {
		return nil
	}
	out := new(KeyStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoreMount) DeepCopyInto(out *KeystoreMount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoreMount.
func (in *KeystoreMount) DeepCopy() *KeystoreMount {
	if in == nil {
		return nil
	}
	out := new(KeystoreMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logging) DeepCopyInto(out *Logging) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging.
func (in *Logging) DeepCopy() *Logging {
	if in == nil {
		return nil
	}
	out := new(Logging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagicLink) DeepCopyInto(out *MagicLink) {
	*out = *in
	out.Parameters = in.Parameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagicLink.
func (in *MagicLink) DeepCopy() *MagicLink {
	if in == nil {
		return nil
	}
	out := new(MagicLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagicLinkParameters) DeepCopyInto(out *MagicLinkParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagicLinkParameters.
func (in *MagicLinkParameters) DeepCopy() *MagicLinkParameters {
	if in == nil {
		return nil
	}
	out := new(MagicLinkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitored) DeepCopyInto(out *Monitored) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitored.
func (in *Monitored) DeepCopy() *Monitored {
	if in == nil {
		return nil
	}
	out := new(Monitored)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	out.Jmx = in.Jmx
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputAdapter) DeepCopyInto(out *OutputAdapter) {
	*out = *in
	out.Email = in.Email
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputAdapter.
func (in *OutputAdapter) DeepCopy() *OutputAdapter {
	if in == nil {
		return nil
	}
	out := new(OutputAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Primary) DeepCopyInto(out *Primary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Primary.
func (in *Primary) DeepCopy() *Primary {
	if in == nil {
		return nil
	}
	out := new(Primary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recaptcha) DeepCopyInto(out *Recaptcha) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recaptcha.
func (in *Recaptcha) DeepCopy() *Recaptcha {
	if in == nil {
		return nil
	}
	out := new(Recaptcha)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rewrite) DeepCopyInto(out *Rewrite) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rewrite.
func (in *Rewrite) DeepCopy() *Rewrite {
	if in == nil {
		return nil
	}
	out := new(Rewrite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Server) DeepCopyInto(out *Server) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Server.
func (in *Server) DeepCopy() *Server {
	if in == nil {
		return nil
	}
	out := new(Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedDb) DeepCopyInto(out *SharedDb) {
	*out = *in
	out.PoolOptions = in.PoolOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedDb.
func (in *SharedDb) DeepCopy() *SharedDb {
	if in == nil {
		return nil
	}
	out := new(SharedDb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedDbPoolOptions) DeepCopyInto(out *SharedDbPoolOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedDbPoolOptions.
func (in *SharedDbPoolOptions) DeepCopy() *SharedDbPoolOptions {
	if in == nil {
		return nil
	}
	out := new(SharedDbPoolOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmsOtp) DeepCopyInto(out *SmsOtp) {
	*out = *in
	out.Parameters = in.Parameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmsOtp.
func (in *SmsOtp) DeepCopy() *SmsOtp {
	if in == nil {
		return nil
	}
	out := new(SmsOtp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmsParameters) DeepCopyInto(out *SmsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmsParameters.
func (in *SmsParameters) DeepCopy() *SmsParameters {
	if in == nil {
		return nil
	}
	out := new(SmsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuperAdmin) DeepCopyInto(out *SuperAdmin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuperAdmin.
func (in *SuperAdmin) DeepCopy() *SuperAdmin {
	if in == nil {
		return nil
	}
	out := new(SuperAdmin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemApplications) DeepCopyInto(out *SystemApplications) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemApplications.
func (in *SystemApplications) DeepCopy() *SystemApplications {
	if in == nil {
		return nil
	}
	out := new(SystemApplications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemRoles) DeepCopyInto(out *SystemRoles) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemRoles.
func (in *SystemRoles) DeepCopy() *SystemRoles {
	if in == nil {
		return nil
	}
	out := new(SystemRoles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateAnnotations) DeepCopyInto(out *TemplateAnnotations) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateAnnotations.
func (in *TemplateAnnotations) DeepCopy() *TemplateAnnotations {
	if in == nil {
		return nil
	}
	out := new(TemplateAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantContext) DeepCopyInto(out *TenantContext) {
	*out = *in
	out.Rewrite = in.Rewrite
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantContext.
func (in *TenantContext) DeepCopy() *TenantContext {
	if in == nil {
		return nil
	}
	out := new(TenantContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantMgt) DeepCopyInto(out *TenantMgt) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantMgt.
func (in *TenantMgt) DeepCopy() *TenantMgt {
	if in == nil {
		return nil
	}
	out := new(TenantMgt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tls) DeepCopyInto(out *Tls) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tls.
func (in *Tls) DeepCopy() *Tls {
	if in == nil {
		return nil
	}
	out := new(Tls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Totp) DeepCopyInto(out *Totp) {
	*out = *in
	out.Parameters = in.Parameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Totp.
func (in *Totp) DeepCopy() *Totp {
	if in == nil {
		return nil
	}
	out := new(Totp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TotpParameters) DeepCopyInto(out *TotpParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TotpParameters.
func (in *TotpParameters) DeepCopy() *TotpParameters {
	if in == nil {
		return nil
	}
	out := new(TotpParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transport) DeepCopyInto(out *Transport) {
	*out = *in
	out.Https = in.Https
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transport.
func (in *Transport) DeepCopy() *Transport {
	if in == nil {
		return nil
	}
	out := new(Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustStore) DeepCopyInto(out *TrustStore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustStore.
func (in *TrustStore) DeepCopy() *TrustStore {
	if in == nil {
		return nil
	}
	out := new(TrustStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDb) DeepCopyInto(out *UserDb) {
	*out = *in
	out.PoolOptions = in.PoolOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDb.
func (in *UserDb) DeepCopy() *UserDb {
	if in == nil {
		return nil
	}
	out := new(UserDb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserPoolOptions) DeepCopyInto(out *UserPoolOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserPoolOptions.
func (in *UserPoolOptions) DeepCopy() *UserPoolOptions {
	if in == nil {
		return nil
	}
	out := new(UserPoolOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserStore) DeepCopyInto(out *UserStore) {
	*out = *in
	out.Properties = in.Properties
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserStore.
func (in *UserStore) DeepCopy() *UserStore {
	if in == nil {
		return nil
	}
	out := new(UserStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserStoreProperties) DeepCopyInto(out *UserStoreProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserStoreProperties.
func (in *UserStoreProperties) DeepCopy() *UserStoreProperties {
	if in == nil {
		return nil
	}
	out := new(UserStoreProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Userstore) DeepCopyInto(out *Userstore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Userstore.
func (in *Userstore) DeepCopy() *Userstore {
	if in == nil {
		return nil
	}
	out := new(Userstore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Userstore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserstoreList) DeepCopyInto(out *UserstoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Userstore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserstoreList.
func (in *UserstoreList) DeepCopy() *UserstoreList {
	if in == nil {
		return nil
	}
	out := new(UserstoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserstoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserstoreProperties) DeepCopyInto(out *UserstoreProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserstoreProperties.
func (in *UserstoreProperties) DeepCopy() *UserstoreProperties {
	if in == nil {
		return nil
	}
	out := new(UserstoreProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserstoreSpec) DeepCopyInto(out *UserstoreSpec) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]UserstoreProperties, len(*in))
		copy(*out, *in)
	}
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserstoreSpec.
func (in *UserstoreSpec) DeepCopy() *UserstoreSpec {
	if in == nil {
		return nil
	}
	out := new(UserstoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserstoreStatus) DeepCopyInto(out *UserstoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserstoreStatus.
func (in *UserstoreStatus) DeepCopy() *UserstoreStatus {
	if in == nil {
		return nil
	}
	out := new(UserstoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Valve) DeepCopyInto(out *Valve) {
	*out = *in
	out.Properties = in.Properties
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Valve.
func (in *Valve) DeepCopy() *Valve {
	if in == nil {
		return nil
	}
	out := new(Valve)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValveProperties) DeepCopyInto(out *ValveProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValveProperties.
func (in *ValveProperties) DeepCopy() *ValveProperties {
	if in == nil {
		return nil
	}
	out := new(ValveProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Valves) DeepCopyInto(out *Valves) {
	*out = *in
	out.Valve = in.Valve
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Valves.
func (in *Valves) DeepCopy() *Valves {
	if in == nil {
		return nil
	}
	out := new(Valves)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wsdl) DeepCopyInto(out *Wsdl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wsdl.
func (in *Wsdl) DeepCopy() *Wsdl {
	if in == nil {
		return nil
	}
	out := new(Wsdl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wso2Is) DeepCopyInto(out *Wso2Is) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wso2Is.
func (in *Wso2Is) DeepCopy() *Wso2Is {
	if in == nil {
		return nil
	}
	out := new(Wso2Is)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Wso2Is) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wso2IsList) DeepCopyInto(out *Wso2IsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Wso2Is, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wso2IsList.
func (in *Wso2IsList) DeepCopy() *Wso2IsList {
	if in == nil {
		return nil
	}
	out := new(Wso2IsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Wso2IsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wso2IsSpec) DeepCopyInto(out *Wso2IsSpec) {
	*out = *in
	out.Configurations = in.Configurations
	if in.KeystoreMounts != nil {
		in, out := &in.KeystoreMounts, &out.KeystoreMounts
		*out = make([]KeystoreMount, len(*in))
		copy(*out, *in)
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wso2IsSpec.
func (in *Wso2IsSpec) DeepCopy() *Wso2IsSpec {
	if in == nil {
		return nil
	}
	out := new(Wso2IsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wso2IsStatus) DeepCopyInto(out *Wso2IsStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wso2IsStatus.
func (in *Wso2IsStatus) DeepCopy() *Wso2IsStatus {
	if in == nil {
		return nil
	}
	out := new(Wso2IsStatus)
	in.DeepCopyInto(out)
	return out
}
