//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminService) DeepCopyInto(out *AdminService) {
	*out = *in
	out.Wsdl = in.Wsdl
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminService.
func (in *AdminService) DeepCopy() *AdminService {
	if in == nil {
		return nil
	}
	out := new(AdminService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth) DeepCopyInto(out *Auth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth.
func (in *Auth) DeepCopy() *Auth {
	if in == nil {
		return nil
	}
	out := new(Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	out.Consent = in.Consent
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authenticator) DeepCopyInto(out *Authenticator) {
	*out = *in
	out.Totp = in.Totp
	out.EmailOtp = in.EmailOtp
	out.SmsOtp = in.SmsOtp
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authenticator.
func (in *Authenticator) DeepCopy() *Authenticator {
	if in == nil {
		return nil
	}
	out := new(Authenticator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpsDatabase) DeepCopyInto(out *BpsDatabase) {
	*out = *in
	out.PoolOptions = in.PoolOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpsDatabase.
func (in *BpsDatabase) DeepCopy() *BpsDatabase {
	if in == nil {
		return nil
	}
	out := new(BpsDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Clustering) DeepCopyInto(out *Clustering) {
	*out = *in
	out.Properties = in.Properties
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Clustering.
func (in *Clustering) DeepCopy() *Clustering {
	if in == nil {
		return nil
	}
	out := new(Clustering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusteringProperties) DeepCopyInto(out *ClusteringProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusteringProperties.
func (in *ClusteringProperties) DeepCopy() *ClusteringProperties {
	if in == nil {
		return nil
	}
	out := new(ClusteringProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configurations) DeepCopyInto(out *Configurations) {
	*out = *in
	out.Server = in.Server
	out.SuperAdmin = in.SuperAdmin
	out.UserStore = in.UserStore
	out.Database = in.Database
	out.Transport = in.Transport
	out.KeyStore = in.KeyStore
	out.TrustStore = in.TrustStore
	out.Monitoring = in.Monitoring
	out.Hazelcast = in.Hazelcast
	out.Authentication = in.Authentication
	out.Recaptcha = in.Recaptcha
	out.OutputAdapter = in.OutputAdapter
	out.Clustering = in.Clustering
	out.TenantMgt = in.TenantMgt
	out.TenantCtx = in.TenantCtx
	out.AdminService = in.AdminService
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configurations.
func (in *Configurations) DeepCopy() *Configurations {
	if in == nil {
		return nil
	}
	out := new(Configurations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Consent) DeepCopyInto(out *Consent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Consent.
func (in *Consent) DeepCopy() *Consent {
	if in == nil {
		return nil
	}
	out := new(Consent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	out.UserDb = in.UserDb
	out.IdentityDb = in.IdentityDb
	out.SharedDb = in.SharedDb
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Database.
func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Datasource) DeepCopyInto(out *Datasource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Datasource.
func (in *Datasource) DeepCopy() *Datasource {
	if in == nil {
		return nil
	}
	out := new(Datasource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Email) DeepCopyInto(out *Email) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Email.
func (in *Email) DeepCopy() *Email {
	if in == nil {
		return nil
	}
	out := new(Email)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailOtp) DeepCopyInto(out *EmailOtp) {
	*out = *in
	out.Parameters = in.Parameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailOtp.
func (in *EmailOtp) DeepCopy() *EmailOtp {
	if in == nil {
		return nil
	}
	out := new(EmailOtp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailOtpParameters) DeepCopyInto(out *EmailOtpParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailOtpParameters.
func (in *EmailOtpParameters) DeepCopy() *EmailOtpParameters {
	if in == nil {
		return nil
	}
	out := new(EmailOtpParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPS) DeepCopyInto(out *HTTPS) {
	*out = *in
	out.Properties = in.Properties
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPS.
func (in *HTTPS) DeepCopy() *HTTPS {
	if in == nil {
		return nil
	}
	out := new(HTTPS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hazelcast) DeepCopyInto(out *Hazelcast) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hazelcast.
func (in *Hazelcast) DeepCopy() *Hazelcast {
	if in == nil {
		return nil
	}
	out := new(Hazelcast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDb) DeepCopyInto(out *IdentityDb) {
	*out = *in
	out.PoolOptions = in.PoolOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDb.
func (in *IdentityDb) DeepCopy() *IdentityDb {
	if in == nil {
		return nil
	}
	out := new(IdentityDb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Internal) DeepCopyInto(out *Internal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Internal.
func (in *Internal) DeepCopy() *Internal {
	if in == nil {
		return nil
	}
	out := new(Internal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Jmx) DeepCopyInto(out *Jmx) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Jmx.
func (in *Jmx) DeepCopy() *Jmx {
	if in == nil {
		return nil
	}
	out := new(Jmx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyStore) DeepCopyInto(out *KeyStore) {
	*out = *in
	out.Primary = in.Primary
	out.Internal = in.Internal
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyStore.
func (in *KeyStore) DeepCopy() *KeyStore {
	if in == nil {
		return nil
	}
	out := new(KeyStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoreMount) DeepCopyInto(out *KeystoreMount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoreMount.
func (in *KeystoreMount) DeepCopy() *KeystoreMount {
	if in == nil {
		return nil
	}
	out := new(KeystoreMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	out.Jmx = in.Jmx
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputAdapter) DeepCopyInto(out *OutputAdapter) {
	*out = *in
	out.Email = in.Email
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputAdapter.
func (in *OutputAdapter) DeepCopy() *OutputAdapter {
	if in == nil {
		return nil
	}
	out := new(OutputAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolOptions) DeepCopyInto(out *PoolOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolOptions.
func (in *PoolOptions) DeepCopy() *PoolOptions {
	if in == nil {
		return nil
	}
	out := new(PoolOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Primary) DeepCopyInto(out *Primary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Primary.
func (in *Primary) DeepCopy() *Primary {
	if in == nil {
		return nil
	}
	out := new(Primary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Properties) DeepCopyInto(out *Properties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Properties.
func (in *Properties) DeepCopy() *Properties {
	if in == nil {
		return nil
	}
	out := new(Properties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recaptcha) DeepCopyInto(out *Recaptcha) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recaptcha.
func (in *Recaptcha) DeepCopy() *Recaptcha {
	if in == nil {
		return nil
	}
	out := new(Recaptcha)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Server) DeepCopyInto(out *Server) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Server.
func (in *Server) DeepCopy() *Server {
	if in == nil {
		return nil
	}
	out := new(Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedDb) DeepCopyInto(out *SharedDb) {
	*out = *in
	out.PoolOptions = in.PoolOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedDb.
func (in *SharedDb) DeepCopy() *SharedDb {
	if in == nil {
		return nil
	}
	out := new(SharedDb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmsOtp) DeepCopyInto(out *SmsOtp) {
	*out = *in
	out.Parameters = in.Parameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmsOtp.
func (in *SmsOtp) DeepCopy() *SmsOtp {
	if in == nil {
		return nil
	}
	out := new(SmsOtp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmsOtpParameters) DeepCopyInto(out *SmsOtpParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmsOtpParameters.
func (in *SmsOtpParameters) DeepCopy() *SmsOtpParameters {
	if in == nil {
		return nil
	}
	out := new(SmsOtpParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepAuthentication) DeepCopyInto(out *StepAuthentication) {
	*out = *in
	out.Authenticator = in.Authenticator
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepAuthentication.
func (in *StepAuthentication) DeepCopy() *StepAuthentication {
	if in == nil {
		return nil
	}
	out := new(StepAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuperAdmin) DeepCopyInto(out *SuperAdmin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuperAdmin.
func (in *SuperAdmin) DeepCopy() *SuperAdmin {
	if in == nil {
		return nil
	}
	out := new(SuperAdmin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLS) DeepCopyInto(out *TLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLS.
func (in *TLS) DeepCopy() *TLS {
	if in == nil {
		return nil
	}
	out := new(TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateAnnotations) DeepCopyInto(out *TemplateAnnotations) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateAnnotations.
func (in *TemplateAnnotations) DeepCopy() *TemplateAnnotations {
	if in == nil {
		return nil
	}
	out := new(TemplateAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantCtx) DeepCopyInto(out *TenantCtx) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantCtx.
func (in *TenantCtx) DeepCopy() *TenantCtx {
	if in == nil {
		return nil
	}
	out := new(TenantCtx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantMgt) DeepCopyInto(out *TenantMgt) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantMgt.
func (in *TenantMgt) DeepCopy() *TenantMgt {
	if in == nil {
		return nil
	}
	out := new(TenantMgt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Totp) DeepCopyInto(out *Totp) {
	*out = *in
	out.Parameters = in.Parameters
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Totp.
func (in *Totp) DeepCopy() *Totp {
	if in == nil {
		return nil
	}
	out := new(Totp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TotpParameters) DeepCopyInto(out *TotpParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TotpParameters.
func (in *TotpParameters) DeepCopy() *TotpParameters {
	if in == nil {
		return nil
	}
	out := new(TotpParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transport) DeepCopyInto(out *Transport) {
	*out = *in
	out.HTTPS = in.HTTPS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transport.
func (in *Transport) DeepCopy() *Transport {
	if in == nil {
		return nil
	}
	out := new(Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustStore) DeepCopyInto(out *TrustStore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustStore.
func (in *TrustStore) DeepCopy() *TrustStore {
	if in == nil {
		return nil
	}
	out := new(TrustStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	out.PoolOptions = in.PoolOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDb) DeepCopyInto(out *UserDb) {
	*out = *in
	out.PoolOptions = in.PoolOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDb.
func (in *UserDb) DeepCopy() *UserDb {
	if in == nil {
		return nil
	}
	out := new(UserDb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserStore) DeepCopyInto(out *UserStore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserStore.
func (in *UserStore) DeepCopy() *UserStore {
	if in == nil {
		return nil
	}
	out := new(UserStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Userstore) DeepCopyInto(out *Userstore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Userstore.
func (in *Userstore) DeepCopy() *Userstore {
	if in == nil {
		return nil
	}
	out := new(Userstore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Userstore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserstoreList) DeepCopyInto(out *UserstoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Userstore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserstoreList.
func (in *UserstoreList) DeepCopy() *UserstoreList {
	if in == nil {
		return nil
	}
	out := new(UserstoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserstoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserstoreProperties) DeepCopyInto(out *UserstoreProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserstoreProperties.
func (in *UserstoreProperties) DeepCopy() *UserstoreProperties {
	if in == nil {
		return nil
	}
	out := new(UserstoreProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserstoreSpec) DeepCopyInto(out *UserstoreSpec) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]UserstoreProperties, len(*in))
		copy(*out, *in)
	}
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserstoreSpec.
func (in *UserstoreSpec) DeepCopy() *UserstoreSpec {
	if in == nil {
		return nil
	}
	out := new(UserstoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserstoreStatus) DeepCopyInto(out *UserstoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserstoreStatus.
func (in *UserstoreStatus) DeepCopy() *UserstoreStatus {
	if in == nil {
		return nil
	}
	out := new(UserstoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wsdl) DeepCopyInto(out *Wsdl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wsdl.
func (in *Wsdl) DeepCopy() *Wsdl {
	if in == nil {
		return nil
	}
	out := new(Wsdl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wso2Is) DeepCopyInto(out *Wso2Is) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wso2Is.
func (in *Wso2Is) DeepCopy() *Wso2Is {
	if in == nil {
		return nil
	}
	out := new(Wso2Is)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Wso2Is) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wso2IsList) DeepCopyInto(out *Wso2IsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Wso2Is, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wso2IsList.
func (in *Wso2IsList) DeepCopy() *Wso2IsList {
	if in == nil {
		return nil
	}
	out := new(Wso2IsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Wso2IsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wso2IsSpec) DeepCopyInto(out *Wso2IsSpec) {
	*out = *in
	out.Configurations = in.Configurations
	if in.KeystoreMounts != nil {
		in, out := &in.KeystoreMounts, &out.KeystoreMounts
		*out = make([]KeystoreMount, len(*in))
		copy(*out, *in)
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wso2IsSpec.
func (in *Wso2IsSpec) DeepCopy() *Wso2IsSpec {
	if in == nil {
		return nil
	}
	out := new(Wso2IsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wso2IsStatus) DeepCopyInto(out *Wso2IsStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wso2IsStatus.
func (in *Wso2IsStatus) DeepCopy() *Wso2IsStatus {
	if in == nil {
		return nil
	}
	out := new(Wso2IsStatus)
	in.DeepCopyInto(out)
	return out
}
